### ISSUE TITLE
Error if I add a context processor

### ISSUE THREAD

**Issue by markhorgan** [rkhleics/wagtailmenus#294] opened 2018-11-08 11:57 UTC
If I add a context processor, wagtailmenus stops working. The error occurs on line 105 of `/models/menus.py` in v2.5.2. I think it has a problem getting `wagtailmenus_vals` from the context. I could use a later version but I currently don't want to have to update wagtail from v1.12.2. I initially tried my own custom context processor and replaced it with `django_settings_export` and tried putting it before and after `wagtailmenus.context_processors.wagtailmenus`. It works fine locally but the problem occurs on the server where I'm using Nginx and uwsgi. I'm using Python 3.6 and Django 1.11.6.

**Comment by ababic** [comment] 2018-11-09 15:14
Hi @markhorgan. Thank you for reporting this issue. 

I'm happy to investigate and see if this is still an issue with the latest supported versions, but if there is a fix, it will be included in the next release, so I'm not sure you'll benefit from it?

If you're on Wagtail 1.12.2 and Django 1.11.6, you should be able to upgrade wagtailmenus as far as 2.10. As with most things, it's advised that you upgrade one minor version at a time, so that you can spot any incompatibility issues as you go. You should be able to find details of any backwards-incompatible changes between versions in the project's [release notes](https://wagtailmenus.readthedocs.io/en/stable/releases/index.html).

**Comment by ababic** [comment] 2018-11-09 15:48
Hi @markhorgan,

I'm afraid I'm unable to reproduce this issue locally. 

The TEMPLATES setting in my development environment looks like this:

```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_ROOT, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'wagtail.contrib.settings.context_processors.settings',
                'wagtailmenus.context_processors.wagtailmenus',
            ],
        },
    },
]
```

And I'm able to move the `wagtailmenus.context_processors.wagtailmenus` item into any position in this list without any problems.

However, if I'm not mistaken, line 105 of `menus.py` in the version you're using seems to make 
 reference to`context['request']` (https://github.com/rkhleics/wagtailmenus/blob/stable/2.5.x/wagtailmenus/models/menus.py#L105), which isn't added by the wagtailmenus context processor. Are you perhaps missing `django.template.context_processors.request` in your version?

**Comment by ababic** [comment] 2018-11-09 15:57
@markhorgan Are you able to share the full stack-trace at all?

**Comment by markhorgan** [comment] 2018-11-09 16:00
Thanks for looking into it. I have `django.template.context_processors.request` in my context_processors. Since the error only occurs on the server, I can only replicate it at a quiet time. I'll get back to you soon with the full stacktrace.

**Closed** 2018-11-23 20:33 UTC

**Comment by markhorgan** [comment] 2019-01-11 20:08
Here's the end of the stacktrace:

```
File "/var/my_website/env/lib/python3.6/site-packages/wagtailmenus/templatetags/menu_tags.py", line 40, in main_menu
    **kwargs
  File "/var/my_website/env/lib/python3.6/site-packages/wagtailmenus/models/menus.py", line 85, in render_from_tag
    ctx_vals = cls.get_contextual_vals_from_context(context)
  File "/var/my_website/env/lib/python3.6/site-packages/wagtailmenus/models/menus.py", line 105, in get_contextual_vals_from_context
    context['request'],
  File "/var/my_website/env/lib/python3.6/site-packages/django/template/context.py", line 87, in __getitem__
    raise KeyError(key)
KeyError: 'request'
```

When it accesses `context['request']` in `Menu.get_contextual_vals_from_context` (models/menus.py) it throws the error. I'm using version 2.5.2.

**Comment by ababic** [comment] 2019-01-12 09:33
Thanks @markhorgan. 

If you are rendering menus from StreamField block templates, then I guess that could explain things. It's hard to understand why that would only happen in production, though.

**Comment by dwasyl** [comment] 2020-01-09 21:46
@markhorgan Did you ever find a solution to this problem? I've run into a similar error and am trying to sort out what's happening.  This is running `wagtailmenus` 2.13.1 and Django 2.2.

**Comment by markhorgan** [comment] 2020-01-10 10:33
@dwasyl No I didn't. I recently created a new site with the latest version of Wagtail (2.6.2), Django (2.2.6) and Wagtailmenus (3.0) and I haven't encountered the problem yet.
