### ISSUE TITLE
Wagtail Permissions & Hiding Menu Options

### ISSUE THREAD

**Issue by dwasyl** [rkhleics/wagtailmenus#120] opened 2017-04-26 19:36 UTC
Now that Wagtail has a much more substantive privacy/permission control system for pages (restricting by logged in users, or by group membership), would it be possible to have menu items hide if the user doesn't have permission to see the page? Presumably any built-in functionality would need to be configurable in some way (since sometimes you'd want to show options someone didn't have permission for).

That said, while there is no current support for this, is there a way I could jury rig this functionality?

**Comment by ababic** [comment] 2017-04-26 21:26
Hi @dwasyl. I'm afraid I'm not familiar with any new permission changes in Wagtail. But, that aside, the rough path for doing something like this would be: 

- Subclass `AbstractMainMenu` and `AbstractFlatMenu` to create your own custom menu models
- Find a way to make instances of those menus aware of the currently logged-in user before they are rendered (no idea how!)
- Override the `top_level_items()` and `pages_for_display()` methods on the custom models to return different Page QuerySets based on the user

Even with this working, only menus defined in the CMS would behave as intended. Other menus wouldn't function the same way, as they use `MenuFromRootPage`, which isn't currently overridable.

**Comment by ababic** [comment] 2017-04-27 13:02
Hi @dwasyl,

I've started work on a PR that should help with all of the above: #121 

With these changes in place, you could simply use settings to swap out all of the various `Menu` classes used for you own versions (subclassing `AbstractMainMenu`, `AbstractFlatMenu`, and `MenuFromRootPage`) and just override `get_base_page_queryset()` on all of them to factor in the current user (available as `self.request.user`)

**Comment by dwasyl** [comment] 2017-04-27 16:20
@ababic in 1.9 Wagtail included some new page privacy features where rather than just the basic password you can required a user be logged in, or be a member of a specific group. Goes a long way to allowing some intranet type functions.

I'll take a look at the new PR. That seems like it could be a relatively simple way of including this type of menu. That was quick, thanks! This gets around your initial concern about `MenuFromRootPage` right? Having to use pre-defined menus would work for now, although that makes one wish for menu items with defined sub-items too. One thing thing at a time though.

**Comment by ababic** [comment] 2017-04-27 17:13
Hey @dwasyl, 

Thanks for the note. I did wonder what the intended use for this would be. It certainly makes sense for something like an intranet. 

Making customisable things aware of the request to give developers more options, is something I've been meaning to do for a while, so I already had an approach in mind. The changes in the PR should be 100% backwards compatible, so shouldn't be too long until they're merged. 

The whole 'definition of sub-menu items' thing is certainly something I've considered. You can 'kinda' hack that in logically in custom MenuItem models, but the interface and tags themselves would need a tonne of reworking.

**Comment by dwasyl** [comment] 2017-04-28 03:20
@ababic Yes, there wouldn't be much use for this in a public site, but on the intranet side of things it could be quite useful.

I've noticed with Wagtail (and menus) the more both page and request are available the more it simplifies life.

I looked at hacking together sub-menu items, but there didn't seem to be a solid approach that I wanted to maintain. Custom sub-menus and changing the order of sub-menus (which could be dealt with by using custom sub-menus) are the two things that I've heard about from people I've set up with `wagtailmenus`.

Now off to try subclassing a menu...

**Comment by ababic** [comment] 2017-04-28 16:09
Hey @dwasyl,

> there didn't seem to be a solid approach that I wanted to maintain

I can definitely relate to that :) Realistically, I don't think this is a problem that I care strongly enough about to develop myself. At least, not at the expense of complicating something that is reasonably simple and works fine/reliably for 90% of cases. I'd rather do the simple things well. I'd be more than willing to review any pull-requests from the community, though.

**Comment by ababic** [comment] 2017-06-21 22:32
Fixed in #121 (merged)

**Closed by ababic** 2017-06-21 22:32 UTC
